/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Bruno Simon <https://threejs-journey.com>
*/

import * as THREE from "three";
import { useRef, useEffect } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

import {
  MeshReflectorMaterial,
  MeshRefractionMaterial,
} from "@react-three/drei";
import { MeshStandardMaterial } from "three";

export default function Model(props) {
  const bakedTexture = useTexture("../../model/bakedBathroomWhite.jpg");
  const { nodes } = useGLTF("../../model//bathroom.glb");
  console.log(nodes);

  //   const textMirror = useTexture("../../image/meduza.jpeg");
  //   textMirror.encoding = THREE.sRGBEncoding;

  return (
    <group {...props} dispose={null}>
      {/* <directionalLight position={[1, 15, 4]} intensity={15.5} />
      <ambientLight intensity={0.5} />
      <mesh
        geometry={nodes.mirror.geometry}
        position={[0.98, 5.66, -5.2]}
        rotation={[Math.PI / 2, 0, 0]}
      >
      
        <MeshReflectorMaterial
          blur={[500, 300]}
          resolution={2048}
          mixBlur={1}
          mixStrength={50}
          roughness={1}
          depthScale={1.2}
          minDepthThreshold={0.4}
          maxDepthThreshold={1.4}
          color="#242038"
          metalness={0.5}
          attach="material"
        />

      </mesh> */}
      <mesh
        geometry={nodes.baked.geometry}
        position={[0.9, 0.34, -1.47]}
        rotation={[0, 0, 0]}
      >
        <meshBasicMaterial map={bakedTexture} map-flipY={false} />
      </mesh>
    </group>
  );
}

// useGLTF.preload("/extra/portal/portal-2.glb");
